<?php
if (!(defined('SITE_ABSOLUTE_ROOT_PATH'))) { 

    if (empty($_SERVER['DOCUMENT_ROOT'])) {

        $WORKING_DIRECTORY = getcwd();

        if ($WORKING_DIRECTORY === false) {
            DEFINE('SITE_ABSOLUTE_ROOT_PATH','');
        } else {
            DEFINE('SITE_ABSOLUTE_ROOT_PATH',$WORKING_DIRECTORY.DIRECTORY_SEPARATOR);
        }

    } else {
        DEFINE('SITE_ABSOLUTE_ROOT_PATH',$_SERVER['DOCUMENT_ROOT'].DIRECTORY_SEPARATOR);
    }
}

if (!(defined('PATH_TO_FRAMEWORK'))) define('PATH_TO_FRAMEWORK',SITE_ABSOLUTE_ROOT_PATH.'NextFrameWork'.DIRECTORY_SEPARATOR);
if (!(defined('PATH_TO_FRAMEWORK_BASECLASS'))) define('PATH_TO_FRAMEWORK_BASECLASS',PATH_TO_FRAMEWORK.'BaseClass'.DIRECTORY_SEPARATOR);
if (!(defined('PATH_TO_FRAMEWORK_DATABASE'))) define('PATH_TO_FRAMEWORK_DATABASE',PATH_TO_FRAMEWORK.'Database'.DIRECTORY_SEPARATOR);
if (!(defined('PATH_TO_FRAMEWORK_DATABASE_INTERFACES'))) define('PATH_TO_FRAMEWORK_DATABASE_INTERFACES',PATH_TO_FRAMEWORK_DATABASE.'Interfaces'.DIRECTORY_SEPARATOR);
if (!(defined('PATH_TO_FRAMEWORK_DATABASE_MYSQL'))) define('PATH_TO_FRAMEWORK_DATABASE_MYSQL',PATH_TO_FRAMEWORK_DATABASE.'Mysql'.DIRECTORY_SEPARATOR);


if (!(defined('PATH_TO_FRAMEWORK_COMPONENT'))) define('PATH_TO_FRAMEWORK_COMPONENT',PATH_TO_FRAMEWORK.'Component'.DIRECTORY_SEPARATOR);
if (!(defined('PATH_TO_FRAMEWORK_WEBCOMPONENT'))) define('PATH_TO_FRAMEWORK_WEBCOMPONENT',PATH_TO_FRAMEWORK.'WebComponent'.DIRECTORY_SEPARATOR);
if (!(defined('PATH_TO_FRAMEWORK_WEBCOMPONENT_FORM'))) define('PATH_TO_FRAMEWORK_WEBCOMPONENT_FORM',PATH_TO_FRAMEWORK_WEBCOMPONENT.'Form'.DIRECTORY_SEPARATOR);
if (!(defined('PATH_TO_FRAMEWORK_WEBCOMPONENT_WEBPAGE'))) define('PATH_TO_FRAMEWORK_WEBCOMPONENT_WEBPAGE',PATH_TO_FRAMEWORK_WEBCOMPONENT.'WebPage'.DIRECTORY_SEPARATOR);
if (!(defined('PATH_TO_FRAMEWORK_WEBCOMPONENT_LIST'))) define('PATH_TO_FRAMEWORK_WEBCOMPONENT_LIST',PATH_TO_FRAMEWORK_WEBCOMPONENT.'List'.DIRECTORY_SEPARATOR);

if (!(defined('PATH_TO_FRAMEWORK_WEBPAYMENTS'))) define('PATH_TO_FRAMEWORK_WEBPAYMENTS',PATH_TO_FRAMEWORK.'WebPayments'.DIRECTORY_SEPARATOR);

// Usato dalla classe per leggere l'input
if (!defined('MAGIC_QUOTE')) define('MAGIC_QUOTE',get_magic_quotes_gpc());
  
?>